from datetime import datetime, timedelta

events_data = [
    {
        "long_url": "https://localhost:3000/event1",
        "name": "Концерт рок-группы 'Импульс'",
        "place": "Крокус Сити Холл",
        "city": "Минск",
        "event_time": (datetime.now() + timedelta(days=7)).isoformat(),
        "price": 2500.00,
        "description": "Грандиозный концерт популярной рок-группы 'Импульс' с новой программой. В программе лучшие хиты и новые композиции.",
        "event_type": "Концерты",
        "message_link": "https://i.pinimg.com/originals/9c/41/77/9c41775391f8e505f26ee2bab7c93bf5.jpg",
        "purchased_count": 0,
        "seats_total": 5000,
        "account_id": 1
    },
    {
        "long_url": "https://localhost:3000/event2",
        "name": "Выставка современного искусства",
        "place": "Третьяковская галерея",
        "city": "Москва",
        "event_time": (datetime.now() + timedelta(days=14)).isoformat(),
        "price": 800.00,
        "description": "Уникальная выставка работ современных российских художников. Более 100 произведений искусства.",
        "event_type": "Обучение",
        "message_link": "https://www.tg-m.ru/img/news2021/tgm_02_08_02.jpg",
        "purchased_count": 0,
        "seats_total": 200,
        "account_id": 1
    },
    {
        "long_url": "https://localhost:3000/event3",
        "name": "Спектакль 'Гамлет'",
        "place": "МХАТ им. Чехова",
        "city": "Москва",
        "event_time": (datetime.now() + timedelta(days=21)).isoformat(),
        "price": 1500.00,
        "description": "Классическая постановка знаменитой трагедии Шекспира в исполнении ведущих актеров театра.",
        "event_type": "Театр",
        "message_link": "https://avatars.mds.yandex.net/i?id=6c3948497fd2e98510e01483149681a1_l-5333586-images-thumbs&n=13",
        "purchased_count": 0,
        "seats_total": 800,
        "account_id": 1
    },
    {
        "long_url": "https://localhost:3000/event4",
        "name": "Фестиваль еды и вина",
        "place": "Парк Горького",
        "city": "Минск",
        "event_time": (datetime.now() + timedelta(days=10)).isoformat(),
        "price": 2000.00,
        "description": "Гастрономический фестиваль с дегустацией блюд от лучших ресторанов города и винных коллекций.",
        "event_type": "Еда",
        "message_link": "https://avatars.mds.yandex.net/i?id=91de45d5b008ef7da377b0a25e354fa64b4c038e-12738984-images-thumbs&n=13",
        "purchased_count": 0,
        "seats_total": 300,
        "account_id": 1
    },
    {
        "long_url": "https://localhost:3000/event5",
        "name": "Мастер-класс по программированию",
        "place": "IT-Академия",
        "city": "Минск",
        "event_time": (datetime.now() + timedelta(days=5)).isoformat(),
        "price": 3000.00,
        "description": "Интенсивный мастер-класс по современным технологиям разработки. Практические задания и разбор кейсов.",
        "event_type": "Обучение",
        "message_link": "https://avatars.mds.yandex.net/i?id=679a7474675a66ccbfea0d3cb651a14605a4b5f4-7086266-images-thumbs&n=13",
        "purchased_count": 0,
        "seats_total": 50,
        "account_id": 1
    },
    {
        "long_url": "https://localhost:3000/event6",
        "name": "Беговой марафон",
        "place": "Центральный парк",
        "city": "Санкт-Петербург",
        "event_time": (datetime.now() + timedelta(days=30)).isoformat(),
        "price": 1500.00,
        "description": "Ежегодный городской марафон. Дистанции: 5км, 10км, 21км, 42км. Для всех уровней подготовки.",
        "event_type": "Фитнес и спорт",
        "message_link": "https://www.m24.ru/b/d/nBkSUhL2h1AvnMe-IL6BrNOp2Z318Ji-mifGnuWR9mOBdDebBizCnTY8qdJf6ReJ58vU9meMMok3Ee2nhSR6ISeO9G1N_wjJ=hTunH_TIbL1VcaALqTuFFg.jpg",
        "purchased_count": 0,
        "seats_total": 1000,
        "account_id": 1
    },
    {
        "long_url": "https://localhost:3000/event7",
        "name": "Джазовый вечер",
        "place": "Джаз-клуб 'Blue Note'",
        "city": "Минск",
        "event_time": (datetime.now() + timedelta(days=3)).isoformat(),
        "price": 1200.00,
        "description": "Вечер живой джазовой музыки в уютной атмосфере. Выступление известных джазовых музыкантов.",
        "event_type": "Концерты",
        "message_link": "https://cdn.concreteplayground.com/content/uploads/2018/12/Restaurant-Hubert_Sydney_credit_Daniel-Boud_supplied-2880x1620.jpg",
        "purchased_count": 0,
        "seats_total": 150,
        "account_id": 1
    },
    {
        "long_url": "https://localhost:3000/event8",
        "name": "Кинофестиваль независимого кино",
        "place": "Кинотеатр 'Октябрь'",
        "city": "Минск",
        "event_time": (datetime.now() + timedelta(days=20)).isoformat(),
        "price": 500.00,
        "description": "Показ лучших независимых фильмов. Встречи с режиссерами и обсуждения после сеансов.",
        "event_type": "Кино",
        "message_link": "https://images.foxtv.com/static.fox5atlanta.com/www.fox5atlanta.com/content/uploads/2024/07/1280/720/GettyImages-1458933210.jpg?ve=1&tl=1",
        "purchased_count": 0,
        "seats_total": 400,
        "account_id": 1
    },
{
        "long_url": "https://localhost:3000/event9",
        "name": "Международная IT-конференция 'Digital Future'",
        "place": "Отель 'Рэдиссон Блу'",
        "city": "Москва",
        "event_time": (datetime.datetime.now() + timedelta(days=90)).isoformat(),
        "price": 15000.00,
        "description": "Ключевые доклады и панельные дискуссии о трендах в области искусственного интеллекта и блокчейна.",
        "event_type": "Обучение",
        "message_link": "https://i.ytimg.com/vi/l4-5zhUi2ME/maxresdefault.jpg",
        "purchased_count": 450,
        "seats_total": 1200,
        "account_id": 1
    },
    {
        "long_url": "https://localhost:3000/event10",
        "name": "Балет 'Лебединое озеро'",
        "place": "Большой театр оперы и балета",
        "city": "Минск",
        "event_time": (datetime.datetime.now() + timedelta(days=14)).isoformat(),
        "price": 8000.00,
        "description": "Классическое исполнение шедевра П.И. Чайковского в 3-х актах.",
        "event_type": "Театр",
        "message_link": "https://avatars.mds.yandex.net/i?id=90c22563dc4697c139288ff6d3400ca4_l-5234975-images-thumbs&n=13",
        "purchased_count": 800,
        "seats_total": 1000,
        "account_id": 2
    },
    {
        "long_url": "https://localhost:3000/event11",
        "name": "Футбольный матч: 'Динамо' против 'Шахтер'",
        "place": "Стадион 'Динамо'",
        "city": "Минск",
        "event_time": (datetime.datetime.now() + timedelta(days=3)).isoformat(),
        "price": 500.00,
        "description": "Принципиальный матч национального чемпионата. Борьба за первое место.",
        "event_type": "Фитнес и спорт",
        "message_link": "https://avatars.mds.yandex.net/i?id=471aa2d7afaebcb995ccd0e86e92c04d_l-4235460-images-thumbs&n=13",
        "purchased_count": 15000,
        "seats_total": 22000,
        "account_id": 3
    },
    {
        "long_url": "https://localhost:3000/event12",
        "name": "Выставка современного искусства 'Цвет и форма'",
        "place": "Национальный художественный музей",
        "city": "Минск",
        "event_time": (datetime.datetime.now() + timedelta(days=21)).isoformat(),
        "price": 300.00,
        "description": "Коллекция работ молодых белорусских художников. Погружение в мир абстракции.",
        "event_type": "Обучение",
        "message_link": "https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_68d1852b5470586957ee1cbb_68d18771e4d3ff41a1655a7e/scale_1200",
        "purchased_count": 120,
        "seats_total": 500,
        "account_id": 4
    },
    {
        "long_url": "https://localhost:3000/event13",
        "name": "Мастер-класс по приготовлению итальянской пасты",
        "place": "Кулинарная студия 'Гастроном'",
        "city": "Минск",
        "event_time": (datetime.datetime.now() + timedelta(hours=48)).isoformat(),
        "price": 4500.00,
        "description": "Освойте секреты настоящей итальянской кухни под руководством шеф-повара.",
        "event_type": "Еда",
        "message_link": "https://www.visitrimini.com/wp-content/uploads/2021/04/z-LARGA1-1.jpg",
        "purchased_count": 15,
        "seats_total": 20,
        "account_id": 1
    },
    {
        "long_url": "https://localhost:3000/event14",
        "name": "Концерт органной музыки Баха и Генделя",
        "place": "Собор Святых Симеона и Елены",
        "city": "Минск",
        "event_time": (datetime.datetime.now() + timedelta(days=60)).isoformat(),
        "price": 1200.00,
        "description": "Вечер классической музыки в неповторимой атмосфере старинного собора.",
        "event_type": "Концерты",
        "message_link": "https://i.ytimg.com/vi/NpNCRvO-hY0/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgUig_MA8=&amp;rs=AOn4CLCH8HHAuMvQgj5HP5VbTXWMF-QXlA",
        "purchased_count": 300,
        "seats_total": 450,
        "account_id": 2
    },
    {
        "long_url": "https://localhost:3000/event15",
        "name": "Семинар 'Эффективные продажи в B2B'",
        "place": "Бизнес-центр 'Виктория'",
        "city": "Минск",
        "event_time": (datetime.datetime.now() + timedelta(days=40)).isoformat(),
        "price": 9500.00,
        "description": "Практические советы и кейсы по увеличению объемов продаж для корпоративного сектора.",
        "event_type": "Обучение",
        "message_link": "https://i.ytimg.com/vi/YVYy7kYQTvg/maxresdefault.jpg",
        "purchased_count": 90,
        "seats_total": 150,
        "account_id": 4
    },
    {
        "long_url": "https://localhost:3000/event16",
        "name": "Джазовый вечер 'Blue Mood'",
        "place": "Клуб 'Граффити'",
        "city": "Минск",
        "event_time": (datetime.datetime.now() + timedelta(days=10)).isoformat(),
        "price": 2000.00,
        "description": "Импровизация и классические джазовые стандарты в исполнении трио 'Swing Time'.",
        "event_type": "Концерты",
        "message_link": "https://blog.way.com/wp-content/uploads/2024/08/AdobeStock_810276832-1-scaled.jpeg",
        "purchased_count": 60,
        "seats_total": 100,
        "account_id": 1
    },
    {
        "long_url": "https://localhost:3000/event17",
        "name": "Детский спектакль 'Приключения Буратино'",
        "place": "Театр юного зрителя",
        "city": "Минск",
        "event_time": (datetime.datetime.now() + timedelta(days=7)).isoformat(),
        "price": 800.00,
        "description": "Яркая постановка по мотивам известной сказки для детей от 3 до 10 лет.",
        "event_type": "Детям",
        "message_link": "https://fs02.vseosvita.ua/0200m6r5-13d3-1200x630.jpg",
        "purchased_count": 250,
        "seats_total": 400,
        "account_id": 2
    }
]

