from datetime import datetime, timedelta

events_data = [
    {
        "long_url": "https://example.com/event1",
        "name": "Концерт рок-группы 'Импульс'",
        "place": "Крокус Сити Холл",
        "city": "Минск",
        "event_time": (datetime.now() + timedelta(days=7)).isoformat(),
        "price": 2500.00,
        "description": "Грандиозный концерт популярной рок-группы 'Импульс' с новой программой. В программе лучшие хиты и новые композиции.",
        "event_type": "Концерт",
        "message_link": "https://avatars.mds.yandex.net/i?id=69019bd7b256edf7de734ccc31d4e857-5666582-images-thumbs&n=13",
        "purchased_count": 0,
        "seats_total": 5000,
        "account_id": 1
    },
    {
        "long_url": "https://example.com/event2",
        "name": "Выставка современного искусства",
        "place": "Третьяковская галерея",
        "city": "Москва",
        "event_time": (datetime.now() + timedelta(days=14)).isoformat(),
        "price": 800.00,
        "description": "Уникальная выставка работ современных российских художников. Более 100 произведений искусства.",
        "event_type": "Выставка",
        "message_link": "https://avatars.mds.yandex.net/i?id=f01e1261162022c6339899a0567016bbb6273a0b-9870356-images-thumbs&n=13",
        "purchased_count": 0,
        "seats_total": 200,
        "account_id": 1
    },
    {
        "long_url": "https://example.com/event3",
        "name": "Спектакль 'Гамлет'",
        "place": "МХАТ им. Чехова",
        "city": "Москва",
        "event_time": (datetime.now() + timedelta(days=21)).isoformat(),
        "price": 1500.00,
        "description": "Классическая постановка знаменитой трагедии Шекспира в исполнении ведущих актеров театра.",
        "event_type": "Театр",
        "message_link": "https://avatars.mds.yandex.net/i?id=bd904c6cad90d45efc50c434e47c5efa6f303c3a-10869728-images-thumbs&n=13",
        "purchased_count": 0,
        "seats_total": 800,
        "account_id": 1
    },
    {
        "long_url": "https://example.com/event4",
        "name": "Фестиваль еды и вина",
        "place": "Парк Горького",
        "city": "Минск",
        "event_time": (datetime.now() + timedelta(days=10)).isoformat(),
        "price": 2000.00,
        "description": "Гастрономический фестиваль с дегустацией блюд от лучших ресторанов города и винных коллекций.",
        "event_type": "Фестиваль",
        "message_link": "https://avatars.mds.yandex.net/i?id=91de45d5b008ef7da377b0a25e354fa64b4c038e-12738984-images-thumbs&n=13",
        "purchased_count": 0,
        "seats_total": 300,
        "account_id": 1
    },
    {
        "long_url": "https://example.com/event5",
        "name": "Мастер-класс по программированию",
        "place": "IT-Академия",
        "city": "Минск",
        "event_time": (datetime.now() + timedelta(days=5)).isoformat(),
        "price": 3000.00,
        "description": "Интенсивный мастер-класс по современным технологиям разработки. Практические задания и разбор кейсов.",
        "event_type": "Образование",
        "message_link": "https://avatars.mds.yandex.net/i?id=679a7474675a66ccbfea0d3cb651a14605a4b5f4-7086266-images-thumbs&n=13",
        "purchased_count": 0,
        "seats_total": 50,
        "account_id": 1
    },
    {
        "long_url": "https://example.com/event6",
        "name": "Беговой марафон",
        "place": "Центральный парк",
        "city": "Санкт-Петербург",
        "event_time": (datetime.now() + timedelta(days=30)).isoformat(),
        "price": 1500.00,
        "description": "Ежегодный городской марафон. Дистанции: 5км, 10км, 21км, 42км. Для всех уровней подготовки.",
        "event_type": "Спорт",
        "message_link": "https://avatars.mds.yandex.net/i?id=fd45f5d1ef297d304d6d70a19c31d1cf-3608855-images-thumbs&ref=rim&n=33&w=250&h=250",
        "purchased_count": 0,
        "seats_total": 1000,
        "account_id": 1
    },
    {
        "long_url": "https://example.com/event7",
        "name": "Джазовый вечер",
        "place": "Джаз-клуб 'Blue Note'",
        "city": "Минск",
        "event_time": (datetime.now() + timedelta(days=3)).isoformat(),
        "price": 1200.00,
        "description": "Вечер живой джазовой музыки в уютной атмосфере. Выступление известных джазовых музыкантов.",
        "event_type": "Концерт",
        "message_link": "https://avatars.mds.yandex.net/i?id=69a569385f6952237167826d3fdcbdf546f9a0bb-6458590-images-thumbs&n=13",
        "purchased_count": 0,
        "seats_total": 150,
        "account_id": 1
    },
    {
        "long_url": "https://example.com/event8",
        "name": "Кинофестиваль независимого кино",
        "place": "Кинотеатр 'Октябрь'",
        "city": "Минск",
        "event_time": (datetime.now() + timedelta(days=20)).isoformat(),
        "price": 500.00,
        "description": "Показ лучших независимых фильмов. Встречи с режиссерами и обсуждения после сеансов.",
        "event_type": "Кино",
        "message_link": "https://blizko.by/ckeditor_assets/pictures/131695/content_oktyabr.jpg",
        "purchased_count": 0,
        "seats_total": 400,
        "account_id": 1
    }
]

